name: Mobile Web RDC Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -X clean install compile test -Dsurefire.suiteXmlFiles=./src/test/resources/AppiumMobileWebRealDevice.xml
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        BUILD_TAG: Github-Java-Appium-Mobile-Web-RDC-1.$GITHUB_RUN_NUMBER
