name: Mobile Web RDC Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '37 13 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -X clean install compile test -Dsurefire.suiteXmlFiles=./src/test/resources/AppiumMobileWebRealDevice.xml
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          BUILD_TAG: Mobile-Web-RDC-1.${{ github.run_number }}
