name: Upload My Demo App monthly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 */30 * *'

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  download_upload_app:
    runs-on: ubuntu-latest
    steps:
      - name: Github Action for curl
        uses: wei/curl@v1.1.1
        with:
          args: -L -o Android-MyDemoAppRN.apk https://github.com/saucelabs/my-demo-app-rn/releases/download/v1.3.0/Android-MyDemoAppRN.1.3.0.build-244.apk
      - run: ls -la