name: Selenium Web Tests GCP

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'
    - cron: '30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install compile test -Dsurefire.suiteXmlFiles=./src/test/resources/SeleniumWeb_GCP.xml -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -V
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME_GCP }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY_GCP }}
          BUILD_TAG: Selenium-GCP-1.${{ github.run_number }}
          TAGS: GCP_TESTING,GCP
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
